### ISSUE TITLE
[dev] Multi-label and Segment Editor Integration

### ISSUE THREAD

**Issue by Zaferyildiz** [bingogome/samm#22] opened 2023-04-16 22:36 UTC
I think it would be great if it is integrated with the segment editor of 3D Slicer. In this way, different segments can be created and labeled according to the masks taken from the SAM model.

**Comment by bingogome** [comment] 2023-04-16 23:15
Thanks for the feedback. The issue is now marked as a dev item.

**Comment by bingogome** [comment] 2023-05-04 21:54
See v1.0.3 release

**Closed by bingogome** 2023-05-04 21:54 UTC
Labels: priority
